set(CPP_PROJECT_TEMPLATE_USING_MSVC FALSE)
set(CPP_PROJECT_TEMPLATE_USING_CLANG FALSE)
set(CPP_PROJECT_TEMPLATE_USING_GCC FALSE)

string(TOLOWER "${CMAKE_CXX_COMPILER_ID}" compiler_id)

if(compiler_id STREQUAL "msvc")
	set(CPP_PROJECT_TEMPLATE_USING_MSVC TRUE)
elseif(compiler_id MATCHES "clang")
	set(CPP_PROJECT_TEMPLATE_USING_CLANG TRUE)
elseif(compiler_id STREQUAL "gnu")
	set(CPP_PROJECT_TEMPLATE_USING_GCC TRUE)
endif()
